import { Hono, type Context } from 'hono';
import { CHANNEL_KINDS, CONVERSATION_MODES, type ApiResult, type RoleCode } from '@abm/contracts';
import { z } from 'zod';
import { background, type Actor, type AppBindings } from '../env';
import { isConstraintFailure } from '../guarded-tx';
import {
  ASSIGNABLE_ROLES, MANAGER_ROLES, ROUND_ROBIN_ROLES, assignConversation, linkBase, loadInboxSettings, type AssignOutcome,
} from './assignment';
import { STAFF_TEXT_MAX, setMode, staffSend } from './conversation-flow';
import { enqueueCommand } from './dispatcher';
import {
  SCHEDULE_TEXT_MAX, approveSchedule, deleteSchedule, getSchedule, listSchedules, pauseSchedule, saveSchedule, submitSchedule,
} from './group-schedules';
import {
  INTAKE_FIELDS, classifyIntake, confirmProposedField, discardIntake, enqueueExtraction, linkIntakeContact, type IntakeFields,
} from './intake';
import { processWorkerCommands } from './worker-commands';

/** Inbox API for the web app. Inbox roles see every conversation of the organization; channel accounts are admin-only. */
export const inboxRoutes = new Hono<AppBindings>();

type Ctx = Context<AppBindings>;

const INBOX_ROLES: ReadonlySet<RoleCode> = new Set(['sale', 'leader', 'head', 'director', 'admin']);
const CONVERSATION_PAGE = 50;
const MESSAGE_PAGE = 200;

const ok = <T>(data: T) => ({ ok: true as const, data });
const fail = (code: string, message: string, extra: Record<string, unknown> = {}) => ({ ok: false as const, error: { code, message, ...extra } });
const forbidden = fail('FORBIDDEN', 'Vai trò hiện tại không xem được mục này');
const notFound = fail('NOT_FOUND', 'Không tìm thấy trong phạm vi của bạn');

async function body<S extends z.ZodType>(c: Ctx, schema: S): Promise<{ data: z.infer<S> } | { error: Response }> {
  const parsed = schema.safeParse(await c.req.json().catch(() => null));
  if (parsed.success) return { data: parsed.data };
  const fields = Object.fromEntries(parsed.error.issues.map((i) => [String(i.path[0] ?? 'form'), i.message]));
  return { error: c.json(fail('VALIDATION_FAILED', 'Dữ liệu không hợp lệ', { fields }), 422) };
}
const invalidQuery = (c: Ctx, field: string) => c.json(fail('VALIDATION_FAILED', 'Dữ liệu không hợp lệ', { fields: { [field]: 'Không hợp lệ' } }), 422);

const auditRow = (db: D1Database, actor: Actor, command: string, entity: string, entityId: string, before: unknown, after: unknown, now: string) =>
  db.prepare(`INSERT INTO audit_log (id, actor_user_id, actor_kind, command, entity, entity_id, before_json, after_json, created_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`).bind(crypto.randomUUID(), actor.id, actor.kind, command, entity, entityId,
    JSON.stringify(before), JSON.stringify(after), now);

const sendTextInput = z.object({
  text: z.string().trim().min(1).max(STAFF_TEXT_MAX),
  /** Generated by the client per composed message and reused on retry, so a resend never sends twice. */
  clientMessageId: z.string().regex(/^[A-Za-z0-9_-]{8,64}$/, 'Không hợp lệ').optional(),
});
const modeInput = z.object({ mode: z.enum(CONVERSATION_MODES) });
const agentKey = z.string().trim().min(1).max(128);
const hhmm = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, 'Định dạng HH:MM');
/** A Zalo number learns its id when it first connects; a Facebook Page is added with its page id and needs no login. */
const createAccountInput = z.object({
  channel: z.enum(CHANNEL_KINDS).default('zalo'),
  displayName: z.string().trim().min(1).max(200),
  agentKey,
  externalId: z.string().trim().regex(/^\d{1,32}$/, 'Page ID là dãy số').optional(),
}).refine((v) => v.channel !== 'facebook' || v.externalId !== undefined, { message: 'Cần Page ID', path: ['externalId'] });
const updateAccountInput = z.object({
  botEnabled: z.boolean().optional(),
  sendPaused: z.boolean().optional(),
  dailySendCap: z.number().int().min(0).max(10_000).optional(),
  quietStart: hhmm.nullable().optional(),
  quietEnd: hhmm.nullable().optional(),
  agentKey: agentKey.optional(),
}).refine((v) => Object.values(v).some((x) => x !== undefined), { message: 'Không có thay đổi' });
const botSwitchInput = z.object({ enabled: z.boolean() });
const userIdInput = z.string().trim().min(1).max(128);
const assignInput = z.object({ userId: userIdInput });
const settingsInput = z.object({
  assignMode: z.enum(['manual', 'round_robin']).optional(),
  slaMinutes: z.number().int().min(1).max(1440).optional(),
  /** The organization-wide switch for recurring group posts; admin only. */
  scheduledSendsEnabled: z.boolean().optional(),
}).refine((v) => v.assignMode !== undefined || v.slaMinutes !== undefined || v.scheduledSendsEnabled !== undefined, { message: 'Không có thay đổi' });
const rosterInput = z.object({ userId: userIdInput, onDuty: z.boolean() });

inboxRoutes.use('*', async (c, next) => {
  if (!INBOX_ROLES.has(c.get('actor').role)) return c.json(forbidden, 403);
  await next();
});
const adminOnly = async (c: Ctx, next: () => Promise<void>) => {
  if (c.get('actor').role !== 'admin') return c.json(forbidden, 403);
  await next();
};
/** Assignment settings and the duty roster are managed by team leaders and admins. */
const SETTINGS_ROLES: ReadonlySet<RoleCode> = new Set(['leader', 'admin']);
const settingsManager = async (c: Ctx, next: () => Promise<void>) => {
  if (!SETTINGS_ROLES.has(c.get('actor').role)) return c.json(forbidden, 403);
  await next();
};
const placeholders = (n: number) => Array.from({ length: n }, () => '?').join(', ');

const CONVERSATION_SELECT = `SELECT c.id, c.channel_account_id AS channelAccountId, a.display_name AS accountName, a.channel,
    c.kind, c.external_thread_id AS externalThreadId, c.contact_id AS contactId, c.display_name AS displayName, c.mode,
    c.assignee_user_id AS assigneeUserId, u.display_name AS assigneeName, c.assigned_at AS assignedAt,
    c.handoff_reason AS handoffReason, c.last_message_at AS lastMessageAt, c.last_inbound_at AS lastInboundAt,
    c.last_staff_reply_at AS lastStaffReplyAt, c.sla_due_at AS slaDueAt, c.created_at AS createdAt, c.updated_at AS updatedAt,
    lm.body AS lastMessageBody, lm.sender_kind AS lastMessageSenderKind, lm.created_at AS lastMessageCreatedAt
  FROM conversation c
  JOIN channel_account a ON a.id = c.channel_account_id
  LEFT JOIN app_user u ON u.id = c.assignee_user_id
  LEFT JOIN message lm ON lm.id = (SELECT m.id FROM message m WHERE m.conversation_id = c.id ORDER BY m.created_at DESC, m.rowid DESC LIMIT 1)`;

const conversationInOrg = (db: D1Database, actor: Actor, id: string) =>
  db.prepare('SELECT id FROM conversation WHERE id = ? AND organization_id = ?').bind(id, actor.organizationId).first<{ id: string }>();

inboxRoutes.get('/conversations', async (c) => {
  const actor = c.get('actor');
  const where = ['c.organization_id = ?'];
  const binds: unknown[] = [actor.organizationId];
  const mode = c.req.query('mode');
  if (mode) {
    if (!(CONVERSATION_MODES as readonly string[]).includes(mode)) return invalidQuery(c, 'mode');
    where.push('c.mode = ?'); binds.push(mode);
  }
  const kind = c.req.query('kind');
  if (kind) {
    if (kind !== 'direct' && kind !== 'group') return invalidQuery(c, 'kind');
    where.push('c.kind = ?'); binds.push(kind);
  }
  const assignee = c.req.query('assignee');
  if (assignee === 'none') where.push('c.assignee_user_id IS NULL');
  else if (assignee) { where.push('c.assignee_user_id = ?'); binds.push(assignee); }
  const account = c.req.query('account');
  if (account) { where.push('c.channel_account_id = ?'); binds.push(account); }
  const q = c.req.query('q')?.trim();
  if (q) {
    where.push("(c.display_name LIKE ? ESCAPE '\\' OR c.external_thread_id = ?)");
    binds.push(`%${q.replace(/[\\%_]/g, (ch) => `\\${ch}`)}%`, q);
  }
  const before = c.req.query('before');
  if (before) { where.push('c.last_message_at < ?'); binds.push(before); }
  const rows = await c.env.DB.prepare(`${CONVERSATION_SELECT} WHERE ${where.join(' AND ')}
    ORDER BY c.last_message_at DESC, c.id DESC LIMIT ?`).bind(...binds, CONVERSATION_PAGE).all();
  return c.json(ok(rows.results));
});

inboxRoutes.get('/conversations/:id', async (c) => {
  const row = await c.env.DB.prepare(`${CONVERSATION_SELECT} WHERE c.id = ? AND c.organization_id = ?`)
    .bind(c.req.param('id'), c.get('actor').organizationId).first();
  return row ? c.json(ok(row)) : c.json(notFound, 404);
});

inboxRoutes.get('/conversations/:id/messages', async (c) => {
  const db = c.env.DB;
  const id = c.req.param('id');
  if (!(await conversationInOrg(db, c.get('actor'), id))) return c.json(notFound, 404);
  const select = `SELECT m.id, m.direction, m.sender_kind AS senderKind, m.sender_external_id AS senderExternalId,
      m.sent_by_user_id AS sentByUserId, u.display_name AS sentByName, m.external_msg_id AS externalMsgId, m.body,
      m.attachments_json AS attachmentsJson, m.status, m.created_at AS createdAt
    FROM message m LEFT JOIN app_user u ON u.id = m.sent_by_user_id WHERE m.conversation_id = ?`;
  const after = c.req.query('after');
  // Without `after` the latest page is returned; either way the list is oldest first.
  const rows = after
    ? (await db.prepare(`${select} AND m.created_at > ? ORDER BY m.created_at, m.rowid LIMIT ?`).bind(id, after, MESSAGE_PAGE).all()).results
    : (await db.prepare(`${select} ORDER BY m.created_at DESC, m.rowid DESC LIMIT ?`).bind(id, MESSAGE_PAGE).all()).results.reverse();
  return c.json(ok(rows));
});

inboxRoutes.post('/conversations/:id/messages', async (c) => {
  const input = await body(c, sendTextInput);
  if ('error' in input) return input.error;
  const sent = await staffSend(c.env.DB, c.get('actor'), c.req.param('id'), input.data.text, input.data.clientMessageId);
  if (!sent) return c.json(notFound, 404);
  if (sent.conflict) return c.json(fail('IDEMPOTENCY_CONFLICT', 'Mã tin nhắn đã dùng cho một tin khác'), 409);
  if (sent.workerCommandQueued) await background(c, processWorkerCommands(c.env));
  const { workerCommandQueued: _queued, conflict: _conflict, ...data } = sent;
  return c.json(ok(data));
});

inboxRoutes.post('/conversations/:id/mode', async (c) => {
  const input = await body(c, modeInput);
  if ('error' in input) return input.error;
  const changed = await setMode(c.env.DB, c.get('actor'), c.req.param('id'), input.data.mode);
  return changed ? c.json(ok(changed)) : c.json(notFound, 404);
});

const ASSIGN_FAILURES: Record<Extract<AssignOutcome, { ok: false }>['reason'], { status: 403 | 404 | 409 | 422; message: string }> = {
  NOT_FOUND: { status: 404, message: 'Không tìm thấy trong phạm vi của bạn' },
  FORBIDDEN: { status: 403, message: 'Nhân viên kinh doanh chỉ tự nhận hội thoại chưa giao' },
  INVALID_ASSIGNEE: { status: 422, message: 'Người nhận không phải nhân viên Inbox đang hoạt động' },
  ALREADY_ASSIGNED: { status: 409, message: 'Hội thoại đã có người nhận' },
};

inboxRoutes.post('/conversations/:id/assign', async (c) => {
  const input = await body(c, assignInput);
  if ('error' in input) return input.error;
  const outcome = await assignConversation(c.env.DB, c.get('actor'), c.req.param('id'), input.data.userId,
    linkBase(c.env.APP_URL, new URL(c.req.url).origin));
  if (!outcome.ok) {
    const failure = ASSIGN_FAILURES[outcome.reason];
    return c.json(fail(outcome.reason, failure.message), failure.status);
  }
  if (outcome.changed) await background(c, processWorkerCommands(c.env));
  return c.json(ok({ assigneeUserId: outcome.assignee.id, assigneeName: outcome.assignee.displayName }));
});

/** Inbox settings plus the recurring group posts switch (off unless an admin turned it on). */
async function loadSettingsView(db: D1Database) {
  const row = await db.prepare('SELECT scheduled_sends_enabled FROM inbox_setting WHERE id = 1').first<{ scheduled_sends_enabled: number }>();
  return { ...(await loadInboxSettings(db)), scheduledSendsEnabled: row?.scheduled_sends_enabled === 1 };
}

inboxRoutes.get('/settings', async (c) => c.json(ok(await loadSettingsView(c.env.DB))));

inboxRoutes.put('/settings', settingsManager, async (c) => {
  const input = await body(c, settingsInput);
  if ('error' in input) return input.error;
  const actor = c.get('actor');
  if (input.data.scheduledSendsEnabled !== undefined && actor.role !== 'admin') {
    return c.json(fail('FORBIDDEN', 'Chỉ quản trị được bật hoặc tắt tin định kỳ'), 403);
  }
  const db = c.env.DB;
  const current = await loadSettingsView(db);
  const next = {
    assignMode: input.data.assignMode ?? current.assignMode,
    slaMinutes: input.data.slaMinutes ?? current.slaMinutes,
    scheduledSendsEnabled: input.data.scheduledSendsEnabled ?? current.scheduledSendsEnabled,
  };
  const now = new Date().toISOString();
  await db.batch([
    db.prepare(`INSERT INTO inbox_setting (id, assign_mode, sla_minutes, scheduled_sends_enabled, updated_by_user_id, updated_at)
      VALUES (1, ?, ?, ?, ?, ?)
      ON CONFLICT(id) DO UPDATE SET assign_mode = excluded.assign_mode, sla_minutes = excluded.sla_minutes,
        scheduled_sends_enabled = excluded.scheduled_sends_enabled,
        updated_by_user_id = excluded.updated_by_user_id, updated_at = excluded.updated_at`)
      .bind(next.assignMode, next.slaMinutes, next.scheduledSendsEnabled ? 1 : 0, actor.id, now),
    auditRow(db, actor, 'inbox.updateSettings', 'inbox_setting', '1',
      { assignMode: current.assignMode, slaMinutes: current.slaMinutes, scheduledSendsEnabled: current.scheduledSendsEnabled }, next, now),
  ]);
  return c.json(ok(await loadSettingsView(db)));
});

/** Active inbox staff (the people a conversation can be assigned to) with their duty flag; `roundRobin` marks who can be on duty. */
inboxRoutes.get('/roster', async (c) => {
  const rows = await c.env.DB.prepare(`SELECT u.id AS userId, u.display_name AS displayName, u.role,
      COALESCE(r.on_duty, 0) AS onDuty, r.last_assigned_at AS lastAssignedAt
    FROM app_user u LEFT JOIN inbox_roster r ON r.user_id = u.id
    WHERE u.organization_id = ? AND u.status = 'active' AND u.role IN (${placeholders(ASSIGNABLE_ROLES.length)})
    ORDER BY u.display_name`).bind(c.get('actor').organizationId, ...ASSIGNABLE_ROLES)
    .all<{ userId: string; displayName: string; role: RoleCode; onDuty: number; lastAssignedAt: string | null }>();
  return c.json(ok(rows.results.map((r) => ({ ...r, onDuty: r.onDuty === 1, roundRobin: ROUND_ROBIN_ROLES.includes(r.role) }))));
});

inboxRoutes.put('/roster', settingsManager, async (c) => {
  const input = await body(c, rosterInput);
  if ('error' in input) return input.error;
  const actor = c.get('actor');
  const db = c.env.DB;
  const user = await db.prepare(`SELECT id FROM app_user
    WHERE id = ? AND organization_id = ? AND status = 'active' AND role IN (${placeholders(ROUND_ROBIN_ROLES.length)})`)
    .bind(input.data.userId, actor.organizationId, ...ROUND_ROBIN_ROLES).first<{ id: string }>();
  if (!user) {
    return c.json(fail('VALIDATION_FAILED', 'Chỉ nhân viên kinh doanh hoặc trưởng nhóm đang hoạt động được xếp trực',
      { fields: { userId: 'Không hợp lệ' } }), 422);
  }
  const before = await db.prepare('SELECT on_duty FROM inbox_roster WHERE user_id = ?').bind(user.id).first<{ on_duty: number }>();
  const onDuty = input.data.onDuty ? 1 : 0;
  const now = new Date().toISOString();
  await db.batch([
    db.prepare(`INSERT INTO inbox_roster (user_id, on_duty) VALUES (?, ?)
      ON CONFLICT(user_id) DO UPDATE SET on_duty = excluded.on_duty`).bind(user.id, onDuty),
    auditRow(db, actor, 'inbox.setDuty', 'inbox_roster', user.id, { onDuty: before?.on_duty === 1 }, { onDuty: onDuty === 1 }, now),
  ]);
  return c.json(ok({ userId: user.id, onDuty: onDuty === 1 }));
});

interface AccountRow {
  id: string; channel: string; externalId: string | null; displayName: string; agentKey: string | null; botEnabled: number;
  sendPaused: number; dailySendCap: number; quietStart: string | null; quietEnd: string | null; status: string;
  qrImage: string | null; qrExpiresAt: string | null; lastSeenAt: string | null; createdAt: string; updatedAt: string;
}
const ACCOUNT_SELECT = `SELECT id, channel, external_id AS externalId, display_name AS displayName, agent_key AS agentKey,
    bot_enabled AS botEnabled, send_paused AS sendPaused, daily_send_cap AS dailySendCap, quiet_start AS quietStart,
    quiet_end AS quietEnd, status, qr_image AS qrImage, qr_expires_at AS qrExpiresAt, last_seen_at AS lastSeenAt,
    created_at AS createdAt, updated_at AS updatedAt
  FROM channel_account`;
/** The login QR signs a company number into the bridge, so only admins receive it. */
const presentAccount = (row: AccountRow, actor: Actor) => ({
  ...row, botEnabled: row.botEnabled === 1, sendPaused: row.sendPaused === 1,
  qrImage: actor.role === 'admin' ? row.qrImage : null,
});
const loadAccount = (db: D1Database, actor: Actor, id: string) =>
  db.prepare(`${ACCOUNT_SELECT} WHERE id = ? AND organization_id = ?`).bind(id, actor.organizationId).first<AccountRow>();

inboxRoutes.get('/accounts', async (c) => {
  const actor = c.get('actor');
  const rows = await c.env.DB.prepare(`${ACCOUNT_SELECT} WHERE organization_id = ? ORDER BY display_name`).bind(actor.organizationId).all<AccountRow>();
  return c.json(ok(rows.results.map((r) => presentAccount(r, actor))));
});

inboxRoutes.post('/accounts', adminOnly, async (c) => {
  const input = await body(c, createAccountInput);
  if ('error' in input) return input.error;
  const actor = c.get('actor');
  const db = c.env.DB;
  const now = new Date().toISOString();
  const id = crypto.randomUUID();
  const { channel, displayName, agentKey: key } = input.data;
  const externalId = channel === 'facebook' ? input.data.externalId! : null;
  const after = { channel, displayName, agentKey: key, externalId };
  try {
    await db.batch([
      db.prepare(`INSERT INTO channel_account (id, organization_id, channel, external_id, display_name, agent_key, status, created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`)
        .bind(id, actor.organizationId, channel, externalId, displayName, key, channel === 'facebook' ? 'connected' : 'disconnected', now, now),
      auditRow(db, actor, 'inbox.createAccount', 'channel_account', id, null, after, now),
    ]);
  } catch (error) {
    if (!isConstraintFailure(error)) throw error;
    return c.json(fail('VALIDATION_FAILED', 'Fanpage này đã được thêm', { fields: { externalId: 'Đã tồn tại' } }), 422);
  }
  return c.json(ok(presentAccount((await loadAccount(db, actor, id))!, actor)));
});

inboxRoutes.patch('/accounts/:id', adminOnly, async (c) => {
  const input = await body(c, updateAccountInput);
  if ('error' in input) return input.error;
  const actor = c.get('actor');
  const db = c.env.DB;
  const current = await loadAccount(db, actor, c.req.param('id')!);
  if (!current) return c.json(notFound, 404);
  const v = input.data;
  const next = {
    botEnabled: v.botEnabled ?? current.botEnabled === 1,
    sendPaused: v.sendPaused ?? current.sendPaused === 1,
    dailySendCap: v.dailySendCap ?? current.dailySendCap,
    quietStart: v.quietStart !== undefined ? v.quietStart : current.quietStart,
    quietEnd: v.quietEnd !== undefined ? v.quietEnd : current.quietEnd,
    agentKey: v.agentKey ?? current.agentKey,
  };
  if ((next.quietStart === null) !== (next.quietEnd === null)) {
    return c.json(fail('VALIDATION_FAILED', 'Giờ yên lặng cần cả giờ bắt đầu và kết thúc', { fields: { quietEnd: 'Thiếu' } }), 422);
  }
  const now = new Date().toISOString();
  const before = {
    botEnabled: current.botEnabled === 1, sendPaused: current.sendPaused === 1, dailySendCap: current.dailySendCap,
    quietStart: current.quietStart, quietEnd: current.quietEnd, agentKey: current.agentKey,
  };
  await db.batch([
    db.prepare(`UPDATE channel_account SET bot_enabled = ?, send_paused = ?, daily_send_cap = ?, quiet_start = ?, quiet_end = ?,
        agent_key = ?, updated_at = ? WHERE id = ?`)
      .bind(next.botEnabled ? 1 : 0, next.sendPaused ? 1 : 0, next.dailySendCap, next.quietStart, next.quietEnd, next.agentKey, now, current.id),
    auditRow(db, actor, 'inbox.updateAccount', 'channel_account', current.id, before, next, now),
  ]);
  return c.json(ok(presentAccount((await loadAccount(db, actor, current.id))!, actor)));
});

/** Queues a bridge login or logout for the account; repeated clicks within the same minute queue one command. */
async function queueSessionCommand(c: Ctx, kind: 'zalo_login' | 'zalo_logout') {
  const actor = c.get('actor');
  const db = c.env.DB;
  const account = await loadAccount(db, actor, c.req.param('id')!);
  if (!account) return c.json(notFound, 404);
  if (account.channel !== 'zalo') return c.json(fail('VALIDATION_FAILED', 'Chỉ tài khoản Zalo đăng nhập qua bridge'), 422);
  const now = new Date();
  const minute = now.toISOString().slice(0, 16);
  const commandId = await enqueueCommand(db, {
    kind, target: 'bridge', channelAccountId: account.id, payload: { accountId: account.id },
    dedupeKey: `${kind === 'zalo_login' ? 'login' : 'logout'}:${account.id}:${minute}`,
  });
  await auditRow(db, actor, kind === 'zalo_login' ? 'inbox.connectAccount' : 'inbox.disconnectAccount', 'channel_account',
    account.id, { status: account.status }, { commandId }, now.toISOString()).run();
  return c.json(ok({ commandId }));
}
inboxRoutes.post('/accounts/:id/connect', adminOnly, (c) => queueSessionCommand(c, 'zalo_login'));
inboxRoutes.post('/accounts/:id/disconnect', adminOnly, (c) => queueSessionCommand(c, 'zalo_logout'));

inboxRoutes.get('/customer-bot-switch', adminOnly, async (c) => {
  const row = await c.env.DB.prepare('SELECT enabled, updated_at FROM customer_bot_switch WHERE id = 1').first<{ enabled: number; updated_at: string | null }>();
  return c.json(ok({ enabled: row?.enabled === 1, updatedAt: row?.updated_at ?? null }));
});

inboxRoutes.put('/customer-bot-switch', adminOnly, async (c) => {
  const input = await body(c, botSwitchInput);
  if ('error' in input) return input.error;
  const actor = c.get('actor');
  const db = c.env.DB;
  const now = new Date().toISOString();
  const before = await db.prepare('SELECT enabled FROM customer_bot_switch WHERE id = 1').first<{ enabled: number }>();
  const enabled = input.data.enabled ? 1 : 0;
  await db.batch([
    db.prepare(`INSERT INTO customer_bot_switch (id, enabled, updated_by_user_id, updated_at) VALUES (1, ?, ?, ?)
      ON CONFLICT(id) DO UPDATE SET enabled = excluded.enabled, updated_by_user_id = excluded.updated_by_user_id, updated_at = excluded.updated_at`)
      .bind(enabled, actor.id, now),
    auditRow(db, actor, 'inbox.setCustomerBotSwitch', 'customer_bot_switch', '1', { enabled: before?.enabled === 1 }, { enabled: enabled === 1 }, now),
  ]);
  return c.json(ok({ enabled: enabled === 1, updatedAt: now }));
});

// ---------- lead intake (ADR-009) ----------

const INTAKE_STATUSES = ['pending', 'classified', 'discarded'] as const;
const INTAKE_PAGE = 100;
const intakeIdInput = z.string().trim().min(1).max(64);
const classifyInput = z.object({
  pipeline: z.enum(['b2b', 'learner']),
  /** The staff form, passed to createLead / createLearnerLead as sent; `source` is set from the channel. */
  input: z.record(z.string(), z.unknown()),
});
const confirmFieldInput = z.object({ field: z.enum(INTAKE_FIELDS) });
const linkContactInput = z.object({ contactId: intakeIdInput });

/** HTTP status of a command error, the same mapping as the command API. */
const COMMAND_STATUS: Partial<Record<string, 403 | 404 | 409 | 422>> = {
  FORBIDDEN: 403, NOT_FOUND: 404, STALE_VERSION: 409, IDEMPOTENCY_CONFLICT: 409, DUPLICATE_SUSPECTED: 409,
  VALIDATION_FAILED: 422, APPROVAL_REQUIRED: 409, KILL_SWITCH_ON: 409,
};
const commandResponse = <T>(c: Ctx, result: ApiResult<T>) =>
  result.ok ? c.json(result) : c.json(result, COMMAND_STATUS[result.error.code] ?? 400);

interface IntakeListRow {
  id: string; conversationId: string; conversationName: string | null; externalThreadId: string; channel: string; accountName: string;
  contactId: string | null; fieldsJson: string; status: string; leadId: string | null; classifiedByUserId: string | null;
  classifiedAt: string | null; createdAt: string; updatedAt: string;
}

/** Intakes of the organization, newest first: `status` (default pending) and optionally one conversation. */
inboxRoutes.get('/intakes', async (c) => {
  const status = c.req.query('status') || 'pending';
  if (!(INTAKE_STATUSES as readonly string[]).includes(status)) return invalidQuery(c, 'status');
  const where = ['i.organization_id = ?', 'i.status = ?'];
  const binds: unknown[] = [c.get('actor').organizationId, status];
  const conversationId = c.req.query('conversationId');
  if (conversationId) { where.push('i.conversation_id = ?'); binds.push(conversationId); }
  const rows = await c.env.DB.prepare(`SELECT i.id, i.conversation_id AS conversationId, c.display_name AS conversationName,
      c.external_thread_id AS externalThreadId, a.channel, a.display_name AS accountName, i.contact_id AS contactId,
      i.fields_json AS fieldsJson, i.status, i.lead_id AS leadId, i.classified_by_user_id AS classifiedByUserId,
      i.classified_at AS classifiedAt, i.created_at AS createdAt, i.updated_at AS updatedAt
    FROM lead_intake i JOIN conversation c ON c.id = i.conversation_id JOIN channel_account a ON a.id = c.channel_account_id
    WHERE ${where.join(' AND ')} ORDER BY i.created_at DESC, i.id DESC LIMIT ?`).bind(...binds, INTAKE_PAGE).all<IntakeListRow>();
  return c.json(ok(rows.results.map(({ fieldsJson, ...row }) => {
    const { proposed = {}, ...values } = JSON.parse(fieldsJson) as IntakeFields;
    return { ...row, fields: values, proposed };
  })));
});

inboxRoutes.post('/intakes/:id/classify', async (c) => {
  const input = await body(c, classifyInput);
  if ('error' in input) return input.error;
  return commandResponse(c, await classifyIntake(c.env.DB, c.get('actor'), c.req.param('id'), input.data));
});

inboxRoutes.post('/intakes/:id/discard', async (c) =>
  commandResponse(c, await discardIntake(c.env.DB, c.get('actor'), c.req.param('id'))));

inboxRoutes.post('/intakes/:id/confirm-field', async (c) => {
  const input = await body(c, confirmFieldInput);
  if ('error' in input) return input.error;
  return commandResponse(c, await confirmProposedField(c.env.DB, c.get('actor'), c.req.param('id'), input.data.field));
});

inboxRoutes.post('/intakes/:id/link-contact', async (c) => {
  const input = await body(c, linkContactInput);
  if ('error' in input) return input.error;
  return commandResponse(c, await linkIntakeContact(c.env.DB, c.get('actor'), c.req.param('id'), input.data.contactId));
});

/** "Cập nhật CRM": asks the extractor to read a direct conversation now. */
inboxRoutes.post('/conversations/:id/extract', async (c) => {
  const actor = c.get('actor');
  const db = c.env.DB;
  const conv = await db.prepare('SELECT id, kind FROM conversation WHERE id = ? AND organization_id = ?')
    .bind(c.req.param('id'), actor.organizationId).first<{ id: string; kind: string }>();
  if (!conv) return c.json(notFound, 404);
  const commandId = conv.kind === 'direct' ? await enqueueExtraction(db, conv.id) : null;
  if (!commandId) return c.json(fail('VALIDATION_FAILED', 'Chỉ trích được hội thoại 1-1 đã có tin nhắn'), 422);
  await auditRow(db, actor, 'inbox.requestExtraction', 'conversation', conv.id, null, { commandId }, new Date().toISOString()).run();
  return c.json(ok({ commandId }));
});

// ---------- Zalo groups and recurring posts ----------

const groupPatchInput = z.object({
  summaryEnabled: z.boolean().optional(),
  scheduledOptOut: z.boolean().optional(),
}).refine((v) => v.summaryEnabled !== undefined || v.scheduledOptOut !== undefined, { message: 'Không có thay đổi' });
const weekdaysMask = z.number().int().min(1).max(127);
const templateText = z.string().trim().min(1).max(SCHEDULE_TEXT_MAX);
const createScheduleInput = z.object({ conversationId: intakeIdInput, templateText, weekdaysMask, timeOfDay: hhmm });
const updateScheduleInput = z.object({ templateText: templateText.optional(), weekdaysMask: weekdaysMask.optional(), timeOfDay: hhmm.optional() })
  .refine((v) => Object.values(v).some((x) => x !== undefined), { message: 'Không có thay đổi' });

interface GroupRow {
  id: string; channelAccountId: string; accountName: string; accountStatus: string; sendPaused: number; externalThreadId: string;
  displayName: string | null; summaryEnabled: number; scheduledOptOut: number; lastMessageAt: string | null; activeSchedules: number;
}
const GROUP_SELECT = `SELECT c.id, c.channel_account_id AS channelAccountId, a.display_name AS accountName, a.status AS accountStatus,
    a.send_paused AS sendPaused, c.external_thread_id AS externalThreadId, c.display_name AS displayName,
    c.summary_enabled AS summaryEnabled, c.scheduled_opt_out AS scheduledOptOut, c.last_message_at AS lastMessageAt,
    (SELECT COUNT(*) FROM group_schedule s WHERE s.conversation_id = c.id AND s.status = 'active') AS activeSchedules
  FROM conversation c JOIN channel_account a ON a.id = c.channel_account_id`;
const GROUP_PAGE = 1000;
const presentGroup = (row: GroupRow) => ({
  ...row, sendPaused: row.sendPaused === 1, summaryEnabled: row.summaryEnabled === 1, scheduledOptOut: row.scheduledOptOut === 1,
});
const loadGroup = (db: D1Database, actor: Actor, id: string) =>
  db.prepare(`${GROUP_SELECT} WHERE c.id = ? AND c.organization_id = ? AND c.kind = 'group'`).bind(id, actor.organizationId).first<GroupRow>();

/** Zalo groups of the organization, by account then name; `account` narrows to one channel account. */
inboxRoutes.get('/groups', async (c) => {
  const actor = c.get('actor');
  const account = c.req.query('account');
  const rows = await c.env.DB.prepare(`${GROUP_SELECT} WHERE c.organization_id = ? AND c.kind = 'group' ${account ? 'AND c.channel_account_id = ?' : ''}
    ORDER BY a.display_name, c.display_name, c.id LIMIT ?`).bind(...(account ? [actor.organizationId, account] : [actor.organizationId]), GROUP_PAGE)
    .all<GroupRow>();
  return c.json(ok(rows.results.map(presentGroup)));
});

/**
 * Daily summary and recurring-post opt-out of a group. Any inbox role may turn summaries on or off and opt a group
 * out; letting recurring posts into a group again takes a manager.
 */
inboxRoutes.patch('/groups/:id', async (c) => {
  const input = await body(c, groupPatchInput);
  if ('error' in input) return input.error;
  const actor = c.get('actor');
  const db = c.env.DB;
  const current = await loadGroup(db, actor, c.req.param('id'));
  if (!current) return c.json(notFound, 404);
  if (input.data.scheduledOptOut === false && current.scheduledOptOut === 1 && !MANAGER_ROLES.has(actor.role)) {
    return c.json(fail('FORBIDDEN', 'Chỉ quản lý được cho nhóm nhận lại tin định kỳ'), 403);
  }
  const next = {
    summaryEnabled: input.data.summaryEnabled ?? current.summaryEnabled === 1,
    scheduledOptOut: input.data.scheduledOptOut ?? current.scheduledOptOut === 1,
  };
  const now = new Date().toISOString();
  await db.batch([
    db.prepare('UPDATE conversation SET summary_enabled = ?, scheduled_opt_out = ?, updated_at = ? WHERE id = ?')
      .bind(next.summaryEnabled ? 1 : 0, next.scheduledOptOut ? 1 : 0, now, current.id),
    auditRow(db, actor, 'inbox.updateGroup', 'conversation', current.id,
      { summaryEnabled: current.summaryEnabled === 1, scheduledOptOut: current.scheduledOptOut === 1 }, next, now),
  ]);
  return c.json(ok(presentGroup((await loadGroup(db, actor, current.id))!)));
});

inboxRoutes.get('/group-schedules', async (c) =>
  c.json(ok(await listSchedules(c.env.DB, c.get('actor'), c.req.query('conversationId') || undefined))));

inboxRoutes.get('/group-schedules/:id', async (c) => {
  const schedule = await getSchedule(c.env.DB, c.get('actor'), c.req.param('id'));
  return schedule ? c.json(ok(schedule)) : c.json(notFound, 404);
});

inboxRoutes.post('/group-schedules', async (c) => {
  const input = await body(c, createScheduleInput);
  if ('error' in input) return input.error;
  return commandResponse(c, await saveSchedule(c.env.DB, c.get('actor'), input.data));
});

inboxRoutes.patch('/group-schedules/:id', async (c) => {
  const input = await body(c, updateScheduleInput);
  if ('error' in input) return input.error;
  return commandResponse(c, await saveSchedule(c.env.DB, c.get('actor'), { id: c.req.param('id'), ...input.data }));
});

inboxRoutes.delete('/group-schedules/:id', async (c) => commandResponse(c, await deleteSchedule(c.env.DB, c.get('actor'), c.req.param('id'))));
inboxRoutes.post('/group-schedules/:id/submit', async (c) => commandResponse(c, await submitSchedule(c.env.DB, c.get('actor'), c.req.param('id'))));
inboxRoutes.post('/group-schedules/:id/approve', async (c) => commandResponse(c, await approveSchedule(c.env.DB, c.get('actor'), c.req.param('id'))));
inboxRoutes.post('/group-schedules/:id/pause', async (c) => commandResponse(c, await pauseSchedule(c.env.DB, c.get('actor'), c.req.param('id'))));

inboxRoutes.all('*', (c) => c.json(notFound, 404));
